; This file was auto-generated by drush make
core = 7.41
api = 2

; Defaults
defaults[projects][subdir] = "contrib"

;Modules
projects[auto_nodetitle][version] = "1.0"
projects[ctools][version] = "1.9"
projects[ckeditor][version] = "1.16"
projects[ckeditor_insert][version] = "1.0-rc1"
projects[custom_formatters][version] = "2.4"
projects[date][version] = "2.9"
projects[devel][version] = "1.5"
projects[ds][version] = "2.11"
projects[ds_bootstrap_layouts][version] = "3.1"
projects[entity][version] = "1.6"
projects[exclude_node_title][version] = "1.9"
projects[faq][version] = "1.1"
projects[field_permissions][version] = "1.0-beta2"
projects[field_tokens][version] = "1.4"
projects[media][version] = "1.5"
projects[fivestar][version] = "2.1"
projects[front][version] = "2.4"
projects[i18n][version] = "1.13"
projects[insert][version] = "1.3"
projects[jquery_update][version] = "3.0-alpha3"
projects[references][version] = "2.1"
projects[nodereference_url][version] = "1.12"
projects[pathauto][version] = "1.3"
projects[pathrules][version] = "1.0"
projects[popup][version] = "1.4"
projects[print][version] = "2.0"
projects[profiler_builder][version] = "1.2"
projects[registration_role][version] = "1.1"
projects[replicate][version] = "1.1"
projects[replicate_ui][version] = "1.4"
projects[role_delegation][version] = "1.1"
projects[rules][version] = "2.9"
projects[smtp][version] = "1.2"
projects[stringoverrides][version] = "1.8"
projects[token][version] = "1.6"
projects[variable][version] = "2.5"
projects[views][version] = "3.11"
projects[views_data_export][version] = "3.0-beta8"
projects[views_export_xls][version] = "1.0"
projects[votingapi][version] = "2.12"

; Themes
projects[bootstrap][version] = "3.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[fatal: Not a git repository (or any parent up to mount point ][download][type] = ""
;projects[fatal: Not a git repository (or any parent up to mount point ][download][url] = ""
;projects[fatal: Not a git repository (or any parent up to mount point ][type] = "theme"

